### ISSUE TITLE
Run on Debian 12

### ISSUE THREAD

**Issue by BuildWithData** [BlockchainCommons/Bitcoin-Standup-Scripts#46] opened 2023-10-07 13:08 UTC
Hi @shannona 

I have tried to run the [standup script ](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/blob/master/Scripts/StandUp.sh) with debian 12 first as you asked [here](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/issues/44) 

I am able to run the script and it seems to work

But there is one problem I have encountered during the execution of the script:

    ./standup.sh - Downloading Bitcoin; this will also take a while!
    wget-log: Permission denied; disabling logging.
    wget-log: Permission denied; disabling logging.
    wget-log: Permission denied; disabling logging.
    ....

I have checked the `standup.log` file and got this:

    >>> cat /standup.log | grep wget-log | wc -l; wc -l /standup.log
    51169
    51983 /standup.log

So in short we have roughly 51k rows with this log message. 

As we can read from the first line I reported above,  these log messages are raised in the bitcoin download section and specifically by the series of wget commands (from row 308 to 312):

    sudo -u standup wget https://bitcoincore.org/bin/$BITCOIN/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz -O ~standup/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz
    sudo -u standup wget https://bitcoincore.org/bin/$BITCOIN/SHA256SUMS.asc -O ~standup/SHA256SUMS.asc
    sudo -u standup wget https://bitcoincore.org/bin/$BITCOIN/SHA256SUMS -O ~standup/SHA256SUMS

    sudo -u standup wget https://raw.githubusercontent.com/bitcoin/bitcoin/23.x/contrib/builder-keys/keys.txt -O ~standup/keys.txt

Not an expert here but I cannot understand why a `Permission denied` error is raised when each `wget` is run as `sudo -u standup`

After this series of logs, I'd expect to find the `standup` folder empty, but instead all files are found:

    >>> ls -l /home/standup/
    total 43164
    -rw-r--r-- 1 standup sudo     2850 Apr 25  2022 SHA256SUMS
    -rw-r--r-- 1 standup sudo    13482 Apr 25  2022 SHA256SUMS.asc
    -rw-r--r-- 1 standup sudo 44173568 Apr 25  2022 bitcoin-23.0-x86_64-linux-gnu.tar.gz
    -rw-r--r-- 1 standup sudo     3591 Oct  7 12:27 keys.txt

I even tried to run this manually like this:

    >>> sudo -u standup mkdir /home/standup/manual
    >>> sudo -u standup wget https://bitcoincore.org/bin/$BITCOIN/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz -O /home/standup/manual/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz

and it worked smoothly without any `wget` log error

any idea ?

**Comment by shannona** [comment] 2023-10-10 19:00
Hey @BuildWithData, thanks for looking into that.

So it looks like wget is now writing log files. `wget-log`, `wget-log.1`, etc. The problem is that when you `sudo` to `~standup` it might end up writing them to a directory where `~standup` doesn't have permissions.

So I tested the script in `/tmp` and it worked fine and I see the logs it created:
```
-rw-r--r-- 1 sudo 65K Oct 10 18:54 /tmp/wget-log
-rw-r--r-- 1 sudo 551 Oct 10 18:54 /tmp/wget-log.1
-rw-r--r-- 1 sudo 227 Oct 10 18:54 /tmp/wget-log.2
```
But I ran it in `/` and it generated exactly the errors you noted.

I think if we add an `-o` option to all the `wget` commands run by standup, and make sure it points to somewhere that `~standup` can  write too, that'll do the trick:
```
       -o logfile
       --output-file=logfile
           Log all messages to logfile.  The messages are normally reported to standard error.
```
maybe `mkdir ~standup/logs` and then `-o ~standup/logs/whatever.log`?

**Comment by BuildWithData** [comment] 2023-10-14 12:29
thanks for the explanation @shannona, opened a pull request [here](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/pull/47)

**Comment by shannona** [comment] 2023-10-17 22:05
Thanks for the very thorough PR. I've tested it through, merged, and updated LBTCftCL too, thanks to your suggestion.

Looking forward to seeing Bitcoin Core 25 as well. Hopefully easy!

**Closed by shannona** 2023-10-17 22:05 UTC

**Comment by BuildWithData** [comment] 2023-10-20 19:03
hi @shannona opened [here](https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts/pull/48)
