### ISSUE TITLE
No host in URI.

### ISSUE THREAD

**Issue by doffing81** [BlockchainCommons/Bitcoin-Standup-Scripts#1] opened 2020-02-19 22:04 UTC
Running the standup script on Ubuntu without passing in any parameters produces a URI without a host onion address.

Tor seems to be running, but I am unable to locate or determine if there is a hidden service set up.

**Comment by Fonta1n3** [comment] 2020-02-26 02:04
Interesting. I saw from your other comments you tried this on Ubuntu 18.04 and that you already had Tor etc installed.

I had tested the scripts on my Ubuntu 18.04 too but had also already configured latest stable Tor prior to that. I wonder if your existing Tor predates V3 hidden services (by default this is true on Ubuntu) and there is some clash there where it added the new V3 hidden service to an incompatible torrc file?

Would you mind sharing the log file with us and deleting any potentially sensitive info from it?

You can get the log by:

`su - root`
`cat standup.log`

**Comment by doffing81** [comment] 2020-02-27 19:27
The log file is rather large, but I can confirm some failed errors:
`gpg: Fatal: can't create directory '/root/.gnupg': Permission denied`
and a:
`cat: /var/lib/tor/standup/hostname: No such file or directory`
which may be significant?

**Comment by Fonta1n3** [comment] 2020-02-28 03:06
yea seems like it either conflicts with your older version of tor or latest stable tor was not installed at all because of the permission error.

**Comment by Fonta1n3** [comment] 2020-03-10 02:03
Just so it is clear these scripts are designed for a fresh install, and are not designed to interact with existing installs. It is on the roadmap to modularize the scripts to work with existing Tor/bitcoind but as it stands users ought to only try the scripts from scratch.

**Comment by Fonta1n3** [comment] 2020-08-21 03:47
closing as outdated and not reproducible. most likely caused by existing tor conflicts.

**Closed by Fonta1n3** 2020-08-21 03:47 UTC
